i2c:
  sda: GPIO0
  scl: GPIO1
  scan: true
  
si4703_fm:
  id: fm_tuner
  address: 0x10 
  reset_pin: GPIO4    
  stc_int_pin: GPIO3 

number:
  - platform: si4703_fm
    si4703_fm_id: fm_tuner
    number_frequency:
      name: "FM Frequency"
      id: fm_frq
      min_value: 87.5
      max_value: 108.0
      step: 0.1
      optimistic: true
    
    number_volume:
      name: "Volume"
      min_value: 0
      max_value: 15
      step: 1
      # Nastavenie na slider
      mode: SLIDER
    
sensor:
  - platform: si4703_fm
    si4703_fm_id: fm_tuner # Uistite sa, že toto ID sedí s vaším hlavným si4703_fm blokom

    # Pôvodný RSSI senzor
    rssi:
      name: "FM RSSI"
      id: fm_rssi
      
    # NOVÉ: SNR Senzor
    snr:
      name: "FM SNR"
      id: fm_snr
      
    # NOVÉ: BLER A Senzor (Chybovosť Bloku A)
    bler_a:
      name: "FM BLER A"
      id: fm_bler_a
      
    # NOVÉ: BLER D Senzor (Chybovosť Bloku D)
    bler_d:
      name: "FM BLER D"
      id: fm_bler_d

switch:
  - platform: si4703_fm
    si4703_fm_id: fm_tuner
    power_switch:
      name: "FM Rádio Power"
      id: fm_power_switch
    mute_switch: # <--- NOVÁ ENTITA
      name: "Rádio Soft Mute"
      id: radio_mute_switch
      icon: mdi:volume-off
    stereo_mono_switch: # <--- NOVÉ
      name: "Režim Mono"
      icon: mdi:surround-sound-2-0
#button:
#  - platform: si4703_seekup
#    name: "FM Seek Up"
#  - platform: si4703_seekdown
#    name: "FM Seek Dwon"
#binary_sensor:
#  - platform: si4703_stereo
#    name: "FM Stereo Prijem"
#    
text_sensor:
  - platform: si4703_fm
    si4703_fm_id: fm_tuner # ID vášho hlavného hubu
    rds_text:
      name: "FM Rádio Text"
      id: fm_rds_text
      icon: mdi:home-assistant
      
    rds_ps:
      name: "FM Názov Stanice"
      id: fm_rds_ps
      icon: mdi:radio
